FROM docker.io/base/archlinux
MAINTAINER Jacek Danecki <jacek.danecki@intel.com>

COPY neo /root/neo
COPY scripts/prepare-arch.sh /root
COPY scripts/build-arch-dep.sh /root

RUN /root/prepare-arch.sh
RUN cd /root; git clone https://github.com/intel/gmmlib gmmlib ;\
    git clone --depth 2 https://github.com/KhronosGroup/OpenCL-Headers khronos ; \
    cd khronos; git checkout -b build e986688daf750633898dfd3994e14a9e618f2aa5 ; cd .. ; \
    cd neo/scripts/igc ; ./prepare.sh ; cd ../../.. ; \
    mkdir build; cd build ; cmake -G Ninja -DBUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Release ../neo ; ninja -j `nproc`
CMD ["/bin/bash"]
